---
- name: Add EPEL yum repository
  ansible.builtin.yum:
    disable_gpg_check: true
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
    state: present

- name: Add MongoDB yum repository
  ansible.builtin.yum_repository:
    name: "mongodb-org-{{ mongodb_version }}"
    description: MongoDB Repository
    baseurl: "https://repo.mongodb.org/yum/redhat/{{ ansible_distribution_major_version }}/mongodb-org/{{ mongodb_version }}/{{ ansible_architecture }}/"
    gpgcheck: true
    enabled: true
    gpgkey: "{{ mongodb_pgp_key_url }}"

- name: Install prerequisite packages
  ansible.builtin.yum:
    name: "{{ redhat_packages }}"
    enablerepo: epel
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
