---
- name: Add Alpine 3.9 repositories
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    line: "{{ line }}"
  loop:
    - https://dl-cdn.alpinelinux.org/alpine/v3.9/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.9/community
  loop_control:
    loop_var: line

- name: Set Java package name
  ansible.builtin.set_fact:
    alpine_packages: "{{ alpine_packages + ['openjdk{{ unifi_java_version }}-jre'] }}"

- name: Install prerequisite packages
  community.general.apk:
    name: "{{ package }}"
    state: latest
    update_cache: true
  loop: "{{ alpine_packages }}"
  loop_control:
    loop_var: package
