---
- name: Enable UniFi Network application system service
  tags:
    - molecule-idempotence-notest
  when:
    - ansible_service_mgr == "systemd"
  ansible.builtin.systemd:
    name: unifi.service
    enabled: true
    state: started

- name: Remove temp directory
  tags:
    - molecule-idempotence-notest
  ansible.builtin.file:
    path: "{{ _temp_dir.path }}"
    state: absent
