---
- name: Enable UniFi Network application system service
  tags:
    - molecule-idempotence-notest
  when:
    - ansible_service_mgr == "systemd"
  ansible.builtin.systemd:
    name: unifi.service
    enabled: true
    state: started

- name: Start UniFi Network application without init system
  tags:
    - molecule-idempotence-notest
  when:
    - ansible_service_mgr != "systemd"
  ansible.builtin.shell:
    executable: /bin/sh
    cmd: /sbin/runuser -u ubnt -- /usr/bin/nohup /usr/bin/java -Xmx1024M -jar ./lib/ace.jar start &
    chdir: "{{ unifi_install_vanity_path }}"
  become: true
  become_user: root
  become_method: ansible.builtin.su

- name: Remove temp directory
  tags:
    - molecule-idempotence-notest
  when: _temp_dir.path is defined
  ansible.builtin.file:
    path: "{{ _temp_dir.path }}"
    state: absent
    unsafe_writes: true
