---
- name: Enable UniFi Network application system service
  tags:
    - molecule-idempotence-notest
  when:
    - ansible_service_mgr == "systemd"
  ansible.builtin.systemd:
    name: unifi.service
    enabled: true
    state: started

- name: Start UniFi Network application without init system
  tags:
    - molecule-idempotence-notest
  when:
    - ansible_service_mgr != "systemd"
  ansible.builtin.shell:
    executable: /bin/sh
    cmd: >
      /usr/bin/java
      -Dfile.encoding=UTF-8
      -Djava.awt.headless=true
      $UNIFI_JVM_OPTS
      --add-opens java.base/java.lang=ALL-UNNAMED
      --add-opens java.base/java.time=ALL-UNNAMED
      --add-opens java.base/sun.security.util=ALL-UNNAMED
      --add-opens java.base/java.io=ALL-UNNAMED
      --add-opens java.rmi/sun.rmi.transport=ALL-UNNAMED
      -jar ./lib/ace.jar start &
    chdir: "{{ unifi_install_vanity_path }}"
  become: true
  become_user: "{{ unifi_user }}"
  become_method: ansible.builtin.su

- name: Remove temp directory
  tags:
    - molecule-idempotence-notest
  when: _temp_dir.path is defined
  ansible.builtin.file:
    path: "{{ _temp_dir.path }}"
    state: absent
    unsafe_writes: true
