---
- name: Enable UniFi Network application system service
  when: ansible_service_mgr == "systemd" and unifi_service_status is true
  ansible.builtin.systemd:
    name: unifi.service
    enabled: true
    state: started
