---
- name: Enable UniFi Network application system service
  tags:
    - molecule-idempotence-notest
  when:
    - ansible_service_mgr == "systemd"
    - ansible_facts.services['unifi.service']
    - ansible_facts.services['unifi.service'].state != "running" or ansible_facts.services['unifi.service'].status != "enabled"
  ansible.builtin.systemd:
    name: unifi.service
    enabled: true
    state: started
