---
- name: Ensure 'unifi_group' exists.
  ansible.builtin.group:
    name: "{{ unifi_group }}"
    state: present

- name: Ensure 'unifi_user' exists.
  ansible.builtin.user:
    name: "{{ unifi_user }}"
    state: present
    group: "{{ unifi_group }}"
