---
dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: rhel8
    image: registry.access.redhat.com/ubi8/ubi-init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    pre_build_image: true
  - name: alpine3
    image: alpine:3.15.0
provisioner:
  name: ansible
  playbooks:
    #create: ../resources/playbooks/create.yml
    #destroy: ../resources/playbooks/destroy.yml
    converge: ../resources/playbooks/converge.yml
    #prepare: ../resources/playbooks/prepare.yml
verifier:
  name: ansible
  directory: ../resources/playbooks/verify.yml
