---
dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
platforms:
  - name: shim
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  create_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
